<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ActivitiesTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('activities')->insert([
            [
                'id' => 1,
                'team_id' => 1,
                'name' => 'Penambahan Core Idle dari history sebelumnya',
                'description' => 'Perbaikan CAV',
                'point' => 3,
                'is_active' => 1,
                'limit_period' => 'monthly',
                'limit_quota' => 10,
                'is_checked_segmen' => 1,
                'requires_photo' => 1,
                'created_at' => Carbon::parse('2025-09-03 10:14:47'),
                'updated_at' => Carbon::parse('2025-09-04 15:36:04'),
            ],
            [
                'id' => 2,
                'team_id' => 1,
                'name' => 'Deklar OP sesuai dan tepat waktu',
                'description' => 'Sesuai dan tepat waktu',
                'point' => 1,
                'is_active' => 1,
                'limit_period' => 'monthly',
                'limit_quota' => 1,
                'is_checked_segmen' => 0,
                'requires_photo' => 1,
                'created_at' => Carbon::parse('2025-09-03 10:14:47'),
                'updated_at' => Carbon::parse('2025-09-04 15:29:33'),
            ],
            [
                'id' => 3,
                'team_id' => 1,
                'name' => 'Menggunakan APD yang sesuai dalam pelaksanaan pekerjaan',
                'description' => 'Isi form setiap akhir shift',
                'point' => 1,
                'is_active' => 1,
                'limit_period' => 'monthly',
                'limit_quota' => 10,
                'is_checked_segmen' => 0,
                'requires_photo' => 1,
                'created_at' => Carbon::parse('2025-09-03 10:14:47'),
                'updated_at' => Carbon::parse('2025-09-04 15:33:14'),
            ],
            [
                'id' => 4,
                'team_id' => 1,
                'name' => 'Menjaga kebersihan OTDR, Splicer, & ALL Tools, submit fotonya setiap',
                'description' => 'Perawatan Tools',
                'point' => 2,
                'is_active' => 1,
                'limit_period' => 'weekly',
                'limit_quota' => 1,
                'is_checked_segmen' => 1,
                'requires_photo' => 1,
                'created_at' => Carbon::parse('2025-09-03 10:14:47'),
                'updated_at' => Carbon::parse('2025-09-04 15:34:42'),
            ],
            [
                'id' => 5,
                'team_id' => 1,
                'name' => 'Kebersihan Serpo',
                'description' => 'Menjaga Kebersihan Serpo',
                'point' => 1,
                'is_active' => 1,
                'limit_period' => 'weekly',
                'limit_quota' => 1,
                'is_checked_segmen' => 0,
                'requires_photo' => 1,
                'created_at' => Carbon::parse('2025-09-03 10:14:47'),
                'updated_at' => Carbon::parse('2025-09-04 15:31:51'),
            ],
            [
                'id' => 6,
                'team_id' => 1,
                'name' => 'Kebersihan Kendaraan Operasional',
                'description' => 'Menjaga kebersihan kendaraan operasional dan selalu dalam kondisi baik siap pakai',
                'point' => 1,
                'is_active' => 1,
                'limit_period' => 'weekly',
                'limit_quota' => 1,
                'is_checked_segmen' => 0,
                'requires_photo' => 1,
                'created_at' => Carbon::parse('2025-09-03 10:14:47'),
                'updated_at' => Carbon::parse('2025-09-05 15:25:13'),
            ],
            [
                'id' => 7,
                'team_id' => 1,
                'name' => 'Laporan Temuan dan perbaikan langsung jika memungkinkan : ',
                'description' => 
                    ' 
                        • SPOF, tiang/kabel unproper, thieft/vandalism, akses issue, dll.
                        • Perapihan KU menjuntai kebawah.
                        • Pemangkasan ranting pohon yang melilit kabel.
                        • Perbaikan Tiang Miring.
                        • Kabel Expose potensi bending/FOC.
                    ',
                'point' => 2,
                'is_active' => 1,
                'limit_period' => 'weekly',
                'limit_quota' => 1,
                'is_checked_segmen' => 0,
                'requires_photo' => 1,
                'created_at' => Carbon::parse('2025-09-03 10:14:47'),
                'updated_at' => Carbon::parse('2025-09-04 16:10:02'),
            ],
            [
                'id' => 8,
                'team_id' => 2,
                'name' => 'Waktu respon pertama (First Response Time)',
                'description' => 'Bersih area sekitar rutin',
                'point' => 8,
                'is_active' => 1,
                'limit_period' => 'monthly',
                'limit_quota' => 30,
                'is_checked_segmen' => 1,
                'requires_photo' => 1,
                'created_at' => Carbon::parse('2025-09-03 10:14:47'),
                'updated_at' => Carbon::parse('2025-09-03 10:14:47'),
            ],
            [
                'id' => 9,
                'team_id' => 2,
                'name' => 'Komunikasi & Etika',
                'description' => 'Bersih area sekitar rutin',
                'point' => 8,
                'is_active' => 1,
                'limit_period' => 'none',
                'limit_quota' => 1,
                'is_checked_segmen' => 0,
                'requires_photo' => 1,
                'created_at' => Carbon::parse('2025-09-03 10:14:47'),
                'updated_at' => Carbon::parse('2025-09-03 10:14:47'),
            ],
            [
                'id' => 10,
                'team_id' => 2,
                'name' => 'Produktivitas',
                'description' => 'Bersih area sekitar rutin',
                'point' => 8,
                'is_active' => 1,
                'limit_period' => 'none',
                'limit_quota' => 1,
                'is_checked_segmen' => 0,
                'requires_photo' => 1,
                'created_at' => Carbon::parse('2025-09-03 10:14:47'),
                'updated_at' => Carbon::parse('2025-09-04 13:38:07'),
            ],
            [
                'id' => 11,
                'team_id' => 2,
                'name' => 'Dokumentasi & Laporan (CIR)',
                'description' => 'Bersih area sekitar rutin',
                'point' => 8,
                'is_active' => 1,
                'limit_period' => 'none',
                'limit_quota' => 1,
                'is_checked_segmen' => 0,
                'requires_photo' => 1,
                'created_at' => Carbon::parse('2025-09-03 10:14:47'),
                'updated_at' => Carbon::parse('2025-09-03 10:14:47'),
            ],
            [
                'id' => 12,
                'team_id' => 1,
                'name' => 'Tidak ada repetititive TT di titik lokasi sama / Link dalam 1 bulan',
                'description' => 'Repetitive Issue',
                'point' => 2,
                'is_active' => 1,
                'limit_period' => 'monthly',
                'limit_quota' => 1,
                'is_checked_segmen' => 1,
                'requires_photo' => 1,
                'created_at' => Carbon::parse('2025-09-04 15:39:08'),
                'updated_at' => Carbon::parse('2025-09-04 15:39:08'),
            ],
            [
                'id' => 13,
                'team_id' => 1,
                'name' => 'Hari dalam bulan, akan dikenakan minus star maksimal 3 kali tidak absen / request attendance',
                'description' => 'Absensi Talenta',
                'point' => 2,
                'is_active' => 1,
                'limit_period' => 'monthLy',
                'limit_quota' => 1,
                'is_checked_segmen' => 1,
                'requires_photo' => 1,
                'created_at' => Carbon::parse('2025-09-04 15:39:08'),
                'updated_at' => Carbon::parse('2025-09-04 15:39:08'),
            ],
            [
                'id' => 14,
                'team_id' => 1,
                'name' => 'Team ke 3 lebih dari 250 km lapomast serpo',
                'description' => 'Support team',
                'point' => 2,
                'is_active' => 1,
                'limit_period' => 'monthly',
                'limit_quota' => 4,
                'is_checked_segmen' => 1,
                'requires_photo' => 1,
                'created_at' => Carbon::parse('2025-09-04 15:40:22'),
                'updated_at' => Carbon::parse('2025-09-04 15:40:22'),
            ],
            [
                'id' => 15,
                'team_id' => 1,
                'name' => 'Full Join & Pengamanan Maksimal 7 hari dari TT, jika tidak ada akan minus star',
                'description' => 'Full Join & Pengamanan After TT',
                'point' => 2,
                'is_active' => 1,
                'limit_period' => 'monthly',
                'limit_quota' => 10,
                'is_checked_segmen' => 0,
                'requires_photo' => 1,
                'created_at' => Carbon::parse('2025-09-04 15:42:49'),
                'updated_at' => Carbon::parse('2025-09-06 20:28:25'),
            ],
        ]);
    }
}
